version: "3.8"

services:
  typesense:
    image: typesense/typesense:0.26.0.rc50
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    env_file:
      - .env
    command:
      ["--data-dir", "/data", "--api-key=${TYPESENSE_API_KEY}", "--enable-cors"]

volumes:
  typesense_data:
